# This is a config for E2B sandbox template.
# You can use template ID (vxn8vqpghlifunn2j6un) or template name (gitwit-empty) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("gitwit-empty") # Sync sandbox
# sandbox = await AsyncSandbox.create("gitwit-empty") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('gitwit-empty')

team_id = "34eab90a-97dc-4be5-87e3-a17b6e6e8bc6"
dockerfile = "e2b.Dockerfile"
template_name = "gitwit-empty"
template_id = "vxn8vqpghlifunn2j6un"
